### ISSUE TITLE
Linux能玩吗？

### ISSUE THREAD

**Issue by jwli6** [Zhuagenborn/Plants-vs.-Zombies-Online-Battle#1]
Linux能玩吗？想在ubuntu上玩…能发布一个Linux上的包文件吗？

**Comment by czs108** [comment]
不是包文件的问题。
植物大战僵尸游戏本身并没有Linux版本，我的代码只是在官方基础上的改进。他们没有提供Linux版本，我也就没办法做。
其次，即使通过一些方法让游戏可以在Linux上运行，但我的代码里面调用了很多Windows的API函数，它们也是没办法在Linux上运行的。

**Comment by chmmm** [comment]
没有中文的reademe吗

**Comment by czs108** [comment]
> 没有中文的reademe吗

没有。之前考虑过加一个中文的，但是代码注释和逆向文档也全是英文，感觉单独加一个中文README意义不大

**Comment by jwli6** [comment]
> 不是包文件的问题。
> 植物大战僵尸游戏本身并没有Linux版本，我的代码只是在官方基础上的改进。他们没有提供Linux版本，我也就没办法做。
> 其次，即使通过一些方法让游戏可以在Linux上运行，但我的代码里面调用了很多Windows的API函数，它们也是没办法在Linux上运行的。

好的，谢谢。
